spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb_dev
    username: dev_user
    password: dev_pass
  flyway:
    enabled: true
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8080